//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamSonVoDao.CoupeQuachVanKe.EntityFrameworkBase2Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriePratiquant
    {
        public int Id { get; set; }
        public string Nom { get; set; }
        public int AgeMax { get; set; }
        public int AgeMin { get; set; }
    
        public virtual Competiteur Competiteur { get; set; }
        public virtual Epreuve Epreuve { get; set; }
    }
}
