//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamSonVoDao.CoupeQuachVanKe.EntityFrameworkBase2Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriePoid
    {
        public int Id { get; set; }
        public string Nom { get; set; }
        public string Description { get; set; }
        public float ValeurBasse { get; set; }
        public float ValeurHaute { get; set; }
        public int EpreuveId { get; set; }
    
        public virtual Epreuve Epreuve { get; set; }
    }
}
