//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamSonVoDao.CoupeQuachVanKe.EntityFrameworkBase2Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competiteur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Competiteur()
        {
            this.Participations = new HashSet<Participation>();
        }
    
        public int Id { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public int Grade { get; set; }
        public System.DateTime DateNaissance { get; set; }
        public int Sexe { get; set; }
        public string LicenceFFKDA { get; set; }
        public int AnneePratique { get; set; }
        public Nullable<int> Poids { get; set; }
        public int NbAnneePratique { get; set; }
        public bool InscritPourQuyen { get; set; }
        public bool InscritPourBaiVuKhi { get; set; }
        public bool InscritPourCombat { get; set; }
        public bool InscritPourSongLuyen { get; set; }
        public bool InscriptionValidePourCoupe { get; set; }
        public bool InscriptionIsCorrect { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual CategoriePratiquant CategoriePratiquant { get; set; }
        public virtual EquipeSongLuyen EquipeSongLuyen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Participation> Participations { get; set; }
    }
}
