//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamSonVoDao.CoupeQuachVanKe.EntityFrameworkBase2Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Epreuve
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Epreuve()
        {
            this.Resultats = new HashSet<Resultat>();
            this.Resultats1 = new HashSet<Resultat>();
            this.Encadrants = new HashSet<Encadrant>();
            this.Competiteurs = new HashSet<Competiteur>();
        }
    
        public int Id { get; set; }
        public string Nom { get; set; }
        public string Description { get; set; }
        public int Statut { get; set; }
        public int TypeEpreuve { get; set; }
        public int Categorie { get; set; }
        public int GenreCategorie { get; set; }
        public int GradeAutorise { get; set; }
        public Nullable<int> Aire_Id { get; set; }
    
        public virtual Aire Aire { get; set; }
        public virtual CategoriePoid CategoriePoid { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resultat> Resultats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resultat> Resultats1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Encadrant> Encadrants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Competiteur> Competiteurs { get; set; }
    }
}
