//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamSonVoDao.CoupeQuachVanKe.EntityFrameworkBase2Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NetClient
    {
        public int Id { get; set; }
        public string ClientName { get; set; }
        public string Password { get; set; }
        public bool IsConnected { get; set; }
        public string Ip { get; set; }
    
        public virtual Aire Aire { get; set; }
        public virtual NetClientType NetClientType { get; set; }
    }
}
