//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamSonVoDao.CoupeQuachVanKe.EntityFrameworkBase2Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resultat
    {
        public int Id { get; set; }
        public bool InscriptionValidee { get; set; }
        public int Classement { get; set; }
        public int Score { get; set; }
        public bool Abandon { get; set; }
        public bool Blessure { get; set; }
        public bool Disqualification { get; set; }
        public bool Absence { get; set; }
        public bool Renvoi { get; set; }
        public int CompetiteurId { get; set; }
        public int EpreuveId { get; set; }
        public Nullable<int> Epreuve_Id1 { get; set; }
    
        public virtual Competiteur Competiteur { get; set; }
        public virtual Epreuve Epreuve { get; set; }
        public virtual Epreuve Epreuve1 { get; set; }
    }
}
