//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamSonVodao.CoupeQuachVanKe.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Club
    {
        public Club()
        {
            this.Competiteurs = new HashSet<Competiteur>();
            this.Competiteurs1 = new HashSet<Competiteur>();
            this.Encadrants = new HashSet<Encadrant>();
            this.Encadrants1 = new HashSet<Encadrant>();
            this.ResponsablesClubs = new HashSet<ResponsablesClub>();
        }
    
        public int Id { get; set; }
        public string Nom { get; set; }
        public string NumeroAffiliation { get; set; }
        public int ResponsableClubId { get; set; }
    
        public virtual ResponsablesClub ResponsablesClub { get; set; }
        public virtual ICollection<Competiteur> Competiteurs { get; set; }
        public virtual ICollection<Competiteur> Competiteurs1 { get; set; }
        public virtual ICollection<Encadrant> Encadrants { get; set; }
        public virtual ICollection<Encadrant> Encadrants1 { get; set; }
        public virtual ICollection<ResponsablesClub> ResponsablesClubs { get; set; }
    }
}
