//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamSonVodao.CoupeQuachVanKe.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupe
    {
        public Coupe()
        {
            this.Aires = new HashSet<Aire>();
            this.Encadrants = new HashSet<Encadrant>();
            this.Medecins = new HashSet<Medecin>();
            this.ResponsablesClubs = new HashSet<ResponsablesClub>();
        }
    
        public int Id { get; set; }
        public string Nom { get; set; }
        public string Description { get; set; }
        public int NombreTapis { get; set; }
        public string Voie { get; set; }
        public Nullable<int> Numero { get; set; }
        public string Complement { get; set; }
        public string CodePostal { get; set; }
        public string Ville { get; set; }
        public System.DateTime DateDebut { get; set; }
        public System.DateTime DateFin { get; set; }
        public Nullable<int> Responsable_Id { get; set; }
    
        public virtual ICollection<Aire> Aires { get; set; }
        public virtual ResponsablesClub ResponsablesClub { get; set; }
        public virtual ICollection<Encadrant> Encadrants { get; set; }
        public virtual ICollection<Medecin> Medecins { get; set; }
        public virtual ICollection<ResponsablesClub> ResponsablesClubs { get; set; }
    }
}
