//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamSonVodao.CoupeQuachVanKe.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Epreuve
    {
        public Epreuve()
        {
            this.CategoriePoids = new HashSet<CategoriePoid>();
            this.Resultats = new HashSet<Resultat>();
            this.Resultats1 = new HashSet<Resultat>();
            this.Competiteurs = new HashSet<Competiteur>();
            this.Encadrants = new HashSet<Encadrant>();
        }
    
        public int Id { get; set; }
        public string Nom { get; set; }
        public string Description { get; set; }
        public int Statut { get; set; }
        public int TypeEpreuve { get; set; }
        public int Categorie { get; set; }
        public int GenreCategorie { get; set; }
        public int GradeAutorise { get; set; }
        public float PoidsMini { get; set; }
        public float PoidsMaxi { get; set; }
        public Nullable<int> Aire_Id { get; set; }
    
        public virtual Aire Aire { get; set; }
        public virtual ICollection<CategoriePoid> CategoriePoids { get; set; }
        public virtual ICollection<Resultat> Resultats { get; set; }
        public virtual ICollection<Resultat> Resultats1 { get; set; }
        public virtual ICollection<Competiteur> Competiteurs { get; set; }
        public virtual ICollection<Encadrant> Encadrants { get; set; }
    }
}
