//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamSonVodao.CoupeQuachVanKe.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medecin
    {
        public int Id { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Telephone { get; set; }
        public string MailContact { get; set; }
        public int CoupeId { get; set; }
    
        public virtual Coupe Coupe { get; set; }
    }
}
