//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamSonVodao.CoupeQuachVanKe.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResponsablesClub
    {
        public ResponsablesClub()
        {
            this.Clubs = new HashSet<Club>();
            this.Coupes = new HashSet<Coupe>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ClubId { get; set; }
        public string Discriminator { get; set; }
        public Nullable<int> CoupeId { get; set; }
    
        public virtual ICollection<Club> Clubs { get; set; }
        public virtual Club Club { get; set; }
        public virtual ICollection<Coupe> Coupes { get; set; }
        public virtual Coupe Coupe { get; set; }
        public virtual Responsable Responsable { get; set; }
    }
}
