//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CategoriesPratiquant {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CategoriesPratiquant() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CategoriesPratiquant", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benjamins.
        /// </summary>
        internal static string Benjamins {
            get {
                return ResourceManager.GetString("Benjamins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadets.
        /// </summary>
        internal static string Cadets {
            get {
                return ResourceManager.GetString("Cadets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juniors.
        /// </summary>
        internal static string Juniors {
            get {
                return ResourceManager.GetString("Juniors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimes.
        /// </summary>
        internal static string Minimes {
            get {
                return ResourceManager.GetString("Minimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Choisissez une catégorie --.
        /// </summary>
        internal static string NotSet {
            get {
                return ResourceManager.GetString("NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pupilles.
        /// </summary>
        internal static string Pupilles {
            get {
                return ResourceManager.GetString("Pupilles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Séniors.
        /// </summary>
        internal static string Seniors {
            get {
                return ResourceManager.GetString("Seniors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vétérans.
        /// </summary>
        internal static string Veterans {
            get {
                return ResourceManager.GetString("Veterans", resourceCulture);
            }
        }
    }
}
