//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamSonVoDao.CoupeQuachVanKe.DataAccessLayer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Grades {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Grades() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LamSonVodao.CoupeQuachVanKe.DataAccessLayer.Resources.Grades", typeof(Grades).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De Ceinture Blanche à 4ème Cap.
        /// </summary>
        public static string CeintureBlancheA4emeCap {
            get {
                return ResourceManager.GetString("CeintureBlancheA4emeCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ceinture Noire.
        /// </summary>
        public static string CeintureNoire {
            get {
                return ResourceManager.GetString("CeintureNoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moins de Ceinture Noire.
        /// </summary>
        public static string MoinsDeCeintureNoire {
            get {
                return ResourceManager.GetString("MoinsDeCeintureNoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade Non Indiqué.
        /// </summary>
        public static string NonRenseigne {
            get {
                return ResourceManager.GetString("NonRenseigne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Choisissez un grade --.
        /// </summary>
        public static string NotSet {
            get {
                return ResourceManager.GetString("NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De 4ème Cap à Ceinture Marron.
        /// </summary>
        public static string Plus4emeCapACeintureMarron {
            get {
                return ResourceManager.GetString("Plus4emeCapACeintureMarron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tous Grades Confondus.
        /// </summary>
        public static string TousGrades {
            get {
                return ResourceManager.GetString("TousGrades", resourceCulture);
            }
        }
    }
}
